ALTER TABLE cursos
    MODIFY COLUMN categoria ENUM('GENERAL', 'PROGRAMACION', 'DESARROLLO_WEB', 'DESARROLLO_SOFTWARE', 
                                 'BASE_DE_DATOS', 'REDES_Y_SEGURIDAD', 'IA_Y_ML', 'CLOUD_COMPUTING', 
                                 'HARDWARE', 'INNOVACIONES_TECNOLOGICAS', 'GAMIFICACION_Y_VIDEOJUEGOS', 
                                 'SOPORTE_TECNICO', 'EDUCACION_EN_TECNOLOGIA', 'TECNOLOGIA_Y_SOCIEDAD') 
    NOT NULL DEFAULT 'GENERAL';